version: '3.6'

services:

    scheduler:
        image: ska-sip-dprepb-c-pipeline
        ports:
            - 8786:8786
            - 8787:8787   
        expose:
            - "2181"
            - "9092"
        entrypoint: ["bash", "./SKA-SIP-DPrepB-C-Pipeline/docker-entrypoint.sh"]
        build:
            context: .
        volumes: 
            - type: bind
              source: ./inputs-docker
              target: /data/inputs
            - type: bind
              source: ./outputs-docker
              target: /data/outputs


    worker:
        image: ska-sip-dprepb-c-pipeline
        hostname: dask-worker
        command: ["dask-worker", "scheduler:8786"]
        build:
            context: .
        expose:
            - "2181"
            - "9092"
        volumes: 
            - type: bind
              source: ./outputs-docker
              target: /data/outputs


    notebook:
        image: ska_notebook
        hostname: notebook
        ports:
            - 8888:8888
        expose:
            - "2181"
            - "9092"
        build:
            context: .
        volumes: 
            - type: bind
              source: ./inputs-docker
              target: /data/inputs
            - type: bind
              source: ./outputs-docker
              target: /data/outputs


    queues:
        image: qa_aggregator
        hostname: queues
        expose:
            - "2181"
            - "9092"
        build:
            context: .
            dockerfile: Dockerfile.queues
        tty: true

