version: '3.6'

services:

    scheduler:
        image: ska-sip-dprepb-c-pipeline
        hostname: dask-scheduler
        ports:
            - 8786:8786
            - 8787:8787
        command: ["dask-scheduler"]
        build: .
        volumes: 
            - type: bind
              source: ./inputs-docker
              target: /data/inputs
            - type: bind
              source: ./outputs-docker
              target: /data/outputs


    worker:
        image: ska-sip-dprepb-c-pipeline
        hostname: dask-worker
        command: ["dask-worker", "scheduler:8786"]
        build: .
        volumes: 
            - type: bind
              source: ./outputs-docker
              target: /data/outputs


    notebook:
        image: ska-sip-dprepb-c-pipeline
        hostname: notebook
        ports:
            - 8888:8888
        build: .
        volumes: 
            - type: bind
              source: ./inputs-docker
              target: /data/inputs
            - type: bind
              source: ./outputs-docker
              target: /data/outputs


